# Generated by Django 2.0.4 on 2018-05-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=75)),
                ('product_url', models.CharField(max_length=150)),
                ('product_nutriscore', models.CharField(max_length=1)),
                ('product_picture', models.ImageField(upload_to='picture/')),
                ('product_ingredient', models.CharField(max_length=300)),
            ],
        ),
    ]
