# Generated by Django 2.0.4 on 2018-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
