# Generated by Django 2.0.4 on 2018-05-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180508_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=75)),
                ('categorie_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Categorie'),
            preserve_default=False,
        ),
    ]
