# Generated by Django 2.0.4 on 2018-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180508_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorie_name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
