# Generated by Django 2.0.4 on 2018-05-13 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_auto_20180508_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_categorie',
        ),
        migrations.AddField(
            model_name='product',
            name='product_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
